MODINVSTOR-1014: Upgrade mac.yml build example
Brew has renamed postgres to postgresql@14: https://formulae.brew.sh/formula/postgresql@14

Brew no longer supports elasticsearch and fails with this error:

```
Error: elasticsearch has been disabled because it is switching to an incompatible license. Check out `opensearch` instead!
```

By default mod-search uses opensearch, therefore the switch to opensearch is reasonable.

Upgrade actions/checkout and actions/setup-java from older version v2 to current version v3.

Use mod-inventory-storage-99999.0.0 to ensure that all install tasks are executed.