MODINVSTOR-982: Improve workaround for Service Point unique failures
The commit 3b6f2455007a7b07d2fa8253798f797a438565fe might not be a thorough enough work-around.
There are still, on rare occassions, causing this problem.
Use the randomly generated UUID to ensure the Service Point is unique between tests.

The exception:
```
17:59:18 [] [test_tenant] [test_user] [mod_inventory_storage] INFO  RestRouting          invoking postLocationUnitsInstitutions
17:59:18 [] [test_tenant] [test_user] [mod_inventory_storage] INFO  LogUtil              127.0.0.1:33152 POST /location-units/institutions null HTTP_1_1 201 303 1 tid=test_tenant Created
17:59:18 [] [test_tenant] [test_user] [mod_inventory_storage] INFO  RestRouting          invoking postLocationUnitsCampuses
17:59:18 [] [test_tenant] [test_user] [mod_inventory_storage] INFO  LogUtil              127.0.0.1:33152 POST /location-units/campuses null HTTP_1_1 201 358 1 tid=test_tenant Created
17:59:18 [] [test_tenant] [test_user] [mod_inventory_storage] INFO  RestRouting          invoking postLocationUnitsLibraries
17:59:18 [] [test_tenant] [test_user] [mod_inventory_storage] INFO  LogUtil              127.0.0.1:33152 POST /location-units/libraries null HTTP_1_1 201 351 1 tid=test_tenant Created
17:59:18 [] [test_tenant] [] [mod_inventory_storage] INFO  RestRouting          invoking postServicePoints
17:59:18 [] [] [] [] WARN  ommitResponseHandler [Consumer clientId=consumer-folio_test-27, groupId=folio_test] Offset commit failed on partition folio.test_tenant.inventory.authority-25 at off
17:59:18 [] [test_tenant] [] [mod_inventory_storage] ERROR ServicePointAPI      ERROR: duplicate key value violates unique constraint "service_point_name_idx_unique" (23505)
io.vertx.pgclient.PgException: ERROR: duplicate key value violates unique constraint "service_point_name_idx_unique" (23505)
  at io.vertx.pgclient.impl.codec.ErrorResponse.toException(ErrorResponse.java:31) ~[vertx-pg-client-4.3.4.jar:4.3.4]
  at io.vertx.pgclient.impl.codec.QueryCommandBaseCodec.handleErrorResponse(QueryCommandBaseCodec.java:57) ~[vertx-pg-client-4.3.4.jar:4.3.4]
  at io.vertx.pgclient.impl.codec.ExtendedQueryCommandCodec.handleErrorResponse(ExtendedQueryCommandCodec.java:90) ~[vertx-pg-client-4.3.4.jar:4.3.4]
  at io.vertx.pgclient.impl.codec.PgDecoder.decodeError(PgDecoder.java:246) ~[vertx-pg-client-4.3.4.jar:4.3.4]
  at io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:132) ~[vertx-pg-client-4.3.4.jar:4.3.4]
  at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:112) ~[vertx-pg-client-4.3.4.jar:4.3.4]
  at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
  at java.lang.Thread.run(Thread.java:829) ~[?:?]
17:59:18 [] [test_tenant] [] [mod_inventory_storage] INFO  LogUtil              127.0.0.1:33152 POST /service-points null HTTP_1_1 422 202 2 tid=test_tenant Unprocessable Entity
17:59:18 [] [test_tenant] [test_user] [mod_inventory_storage] INFO  RestRouting          invoking postLocations
```