MODINVSTOR-754: Sporadic await ConditionTimeoutException in DomainEventAssertions
Builds on Jenkins have sporadic failures:

https://jenkins-aws.indexdata.com/blue/organizations/jenkins/folio-org%2Fmod-inventory-storage/detail/PR-648/1/pipeline/

canPostSynchronousBatchWithExistingIdUpsertTrue(org.folio.rest.api.ItemStorageTest) Time elapsed: 1.101 sec <<< ERROR!

org.awaitility.core.ConditionTimeoutException: Lambda expression in org.folio.rest.support.matchers.DomainEventAssertions that uses java.lang.String, java.lang.Stringjava.lang.String: expected a value greater than <0> but <0> was equal to <0> within 1 seconds.

 at org.folio.rest.api.ItemStorageTest.canPostSynchronousBatchWithExistingIdUpsertTrue(ItemStorageTest.java:1051)

https://jenkins-aws.indexdata.com/blue/organizations/jenkins/folio-org%2Fmod-inventory-storage/detail/PR-648/2/pipeline/

canDeleteAnItem(org.folio.rest.api.ItemStorageTest) Time elapsed: 1.074 sec <<< ERROR!

org.awaitility.core.ConditionTimeoutException: Lambda expression in org.folio.rest.support.matchers.DomainEventAssertions that uses java.lang.String, java.lang.Stringjava.lang.String: expected a value greater than <1> but <1> was equal to <1> within 1 seconds.

 at org.folio.rest.api.ItemStorageTest.canDeleteAnItem(ItemStorageTest.java:1530)

https://jenkins-aws.indexdata.com/blue/organizations/jenkins/folio-org%2Fmod-inventory-storage/detail/folijet-rancher/18/pipeline/

canCreateAnItemViaCollectionResource(org.folio.rest.api.ItemStorageTest) Time elapsed: 1.034 sec <<< ERROR!

org.awaitility.core.ConditionTimeoutException: Lambda expression in org.folio.rest.support.matchers.DomainEventAssertions that uses java.lang.String, java.lang.Stringjava.lang.String: expected a value greater than <0> but <0> was equal to <0> within 1 seconds.

 at org.folio.rest.api.ItemStorageTest.canCreateAnItemViaCollectionResource(ItemStorageTest.java:291)

The timeout of 1 second might be too small, therefore it is removed to use the default await() timeout of 10 seconds.